apiVersion: v1
kind: Service
metadata:
  name: flaskservice
spec:
  containers:
  - name: flaskapp
    image: cks1130cks/flaskapp:latest
    ports:
    - containerPort: 5000
  imagePullSecrets:
  - name: scret
