apiVersion: v1
kind: pod
metadata:
  name: flask
  labels:
    app: flaskapp
spec:
  containers:
  - name: flaskapp
    image: cks1130cks/flaskapp:latest
    ports:
    - containerPort: 5000
  imagePullSecrets:
  - name: scret
